let products=[
   {
      productname:"laptop",
      brand:"hp",
      price:"35000",
      rating:"10",
      img:"1234.jpg"
   },
   {
      productname:"laptop",
      brand:"dell",
      price:"35000",
      rating:"9.8",
      img:"1234.jpg"
   },
   {
      productname:"laptop",
      brand:"lenovo",
      price:"35000",
      rating:"9.9",
      img:"1234.jpg"
   },
   {
      productname:"laptop",
      brand:"hp",
      price:"35000",
      rating:"10",
      img:"1234.jpg"
   },
   {
      productname:"laptop",
      brand:"dell",
      price:"35000",
      rating:"9.8"
   },
   {
      productname:"laptop",
      brand:"lenovo",
      price:"35000",
      rating:"9.9"
   },
   {
      productname:"laptop",
      brand:"hp",
      price:"35000",
      rating:"10"
   },
   {
      productname:"laptop",
      brand:"dell",
      price:"35000",
      rating:"9.8"
   },
   {
      productname:"laptop",
      brand:"lenovo",
      price:"35000",
      rating:"9.9"
   },
   {
      productname:"laptop",
      brand:"hp",
      price:"35000",
      rating:"10"
   }
]

let image=document.getElementsByClassName('image')
let title=document.getElementsByClassName('title')
let price=document.getElementsByClassName('price')
for(let i=0;i<products.length;i++){
   //image[i].src=products[i].img
   title[i].textContent=products[i].productname
   price[i].textContent=products[i].price
}
